### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by benjaminirving** [JeGa/Branch-And-Mincut#1]
Hi, 

Thanks for making this code available. It would be useful to have a README to explain the implementation a bit more and some sort of licence.

**Comment by JeGa** [comment]
Hi,

I added some information to the repository. Let me know if you have any further questions.

**Comment by benjaminirving** [comment]
Thanks very much.

**Comment by roaasoloh** [comment]
Dear Sir,
Thank you for this code.
I appreciate it if there is anyone to reach you for better clarifications regarding the code.
Or it's proper to ask here?
